[package]
name = "tonic_demo"
version = "0.1.0"
authors = ["will <64425242+willser@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
